#!/usr/bin/env python3
"""Generate data/seed.sql -- the sample database for the SQL Quest learning app.

The output is deterministic (fixed PRNG seed) so that every lesson, example and
graded exercise sees exactly the same data on every machine. Re-run with:

    python3 tools/generate_seed.py

The generated file is committed to the repository; the app fetches it at runtime.
"""
from __future__ import annotations

import datetime as dt
import random
from pathlib import Path

RNG = random.Random(20240501)
TODAY = dt.date(2025, 6, 30)          # "now" for every date-based lesson
OUT = Path(__file__).resolve().parent.parent / "data" / "seed.sql"


def q(value) -> str:
    """Render a Python value as a SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int,)):
        return str(value)
    if isinstance(value, float):
        return f"{value:.2f}"
    return "'" + str(value).replace("'", "''") + "'"


def row(values) -> str:
    return "(" + ", ".join(q(v) for v in values) + ")"


def insert(table: str, columns: list[str], rows: list[list]) -> str:
    """Multi-row INSERT, chunked so no single statement gets unwieldy."""
    out = []
    for i in range(0, len(rows), 50):
        chunk = rows[i:i + 50]
        head = f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n"
        out.append(head + ",\n".join("  " + row(r) for r in chunk) + ";\n")
    return "\n".join(out)


def d(date: dt.date) -> str:
    return date.isoformat()


def ts(date: dt.date, hour: int, minute: int, second: int = 0) -> str:
    return f"{date.isoformat()} {hour:02d}:{minute:02d}:{second:02d}"


# --------------------------------------------------------------------------
# Reference data
# --------------------------------------------------------------------------

COUNTRIES = [
    ("USA", ["Seattle", "Austin", "Boston", "Denver", "Chicago", "Portland"]),
    ("Canada", ["Toronto", "Montreal", "Vancouver"]),
    ("UK", ["London", "Manchester", "Bristol"]),
    ("Germany", ["Berlin", "Hamburg", "Munich"]),
    ("France", ["Paris", "Lyon"]),
    ("Japan", ["Tokyo", "Osaka"]),
    ("Brazil", ["Sao Paulo", "Rio de Janeiro"]),
    ("Australia", ["Sydney", "Melbourne"]),
    ("Singapore", ["Singapore"]),
    ("Sweden", ["Stockholm"]),
]

FIRST_NAMES = [
    "Ada", "Bruno", "Camila", "Dmitri", "Elena", "Farid", "Grace", "Hana",
    "Ibrahim", "Jonas", "Keiko", "Luis", "Maya", "Noor", "Oscar", "Priya",
    "Quinn", "Rosa", "Samir", "Tariq", "Ulla", "Viktor", "Wen", "Xiomara",
    "Yusuf", "Zara", "Anders", "Bianca", "Caleb", "Dalia", "Emil", "Fiona",
    "Gustav", "Helena", "Ines", "Jasper", "Kira", "Leon", "Mira", "Nadia",
]

LAST_NAMES = [
    "Alvarez", "Bergstrom", "Chen", "Dubois", "Eriksen", "Ferreira", "Gupta",
    "Haddad", "Ivanov", "Johansson", "Kowalski", "Lindqvist", "Moreau",
    "Nakamura", "Okafor", "Petrov", "Quintana", "Rossi", "Silva", "Tanaka",
    "Ueda", "Vargas", "Weber", "Xu", "Yilmaz", "Zielinski", "Brennan",
    "Costa", "Delgado", "Novak",
]

TIERS = ["bronze", "silver", "gold", "platinum"]
STATUSES = ["completed", "completed", "completed", "completed", "shipped",
            "processing", "cancelled", "returned"]
METHODS = ["credit_card", "credit_card", "paypal", "bank_transfer", "gift_card"]
DEVICES = ["desktop", "mobile", "mobile", "tablet"]

# --------------------------------------------------------------------------
# Schema
# --------------------------------------------------------------------------

SCHEMA = """-- =====================================================================
--  SQL Quest -- sample database  (generated by tools/generate_seed.py)
--
--  A small online music-gear store: catalogue, customers, staff, orders,
--  payments, reviews and web traffic. Everything a SQL learner needs:
--  foreign keys, NULLs, a self-referencing employee hierarchy, a nested
--  category tree, dates, money and a JSON column.
-- =====================================================================

PRAGMA foreign_keys = ON;

CREATE TABLE categories (
  category_id   INTEGER PRIMARY KEY,
  name          TEXT    NOT NULL,
  parent_id     INTEGER REFERENCES categories(category_id)
);

CREATE TABLE suppliers (
  supplier_id   INTEGER PRIMARY KEY,
  name          TEXT    NOT NULL,
  country       TEXT    NOT NULL,
  city          TEXT,
  lead_time_days INTEGER NOT NULL,
  rating        REAL
);

CREATE TABLE products (
  product_id    INTEGER PRIMARY KEY,
  name          TEXT    NOT NULL,
  category_id   INTEGER NOT NULL REFERENCES categories(category_id),
  supplier_id   INTEGER REFERENCES suppliers(supplier_id),
  unit_price    REAL    NOT NULL CHECK (unit_price >= 0),
  units_in_stock INTEGER NOT NULL DEFAULT 0,
  reorder_level INTEGER,
  discontinued  INTEGER NOT NULL DEFAULT 0 CHECK (discontinued IN (0, 1)),
  released_on   TEXT
);

CREATE TABLE product_meta (
  product_id    INTEGER PRIMARY KEY REFERENCES products(product_id),
  attributes    TEXT NOT NULL          -- JSON document
);

CREATE TABLE customers (
  customer_id   INTEGER PRIMARY KEY,
  first_name    TEXT    NOT NULL,
  last_name     TEXT    NOT NULL,
  email         TEXT    NOT NULL UNIQUE,
  country       TEXT,
  city          TEXT,
  signup_date   TEXT    NOT NULL,
  birth_date    TEXT,
  loyalty_tier  TEXT    NOT NULL DEFAULT 'bronze',
  referred_by   INTEGER REFERENCES customers(customer_id)
);

CREATE TABLE employees (
  employee_id   INTEGER PRIMARY KEY,
  first_name    TEXT    NOT NULL,
  last_name     TEXT    NOT NULL,
  title         TEXT    NOT NULL,
  department    TEXT    NOT NULL,
  manager_id    INTEGER REFERENCES employees(employee_id),
  hire_date     TEXT    NOT NULL,
  salary        REAL    NOT NULL,
  region        TEXT
);

CREATE TABLE orders (
  order_id      INTEGER PRIMARY KEY,
  customer_id   INTEGER NOT NULL REFERENCES customers(customer_id),
  employee_id   INTEGER REFERENCES employees(employee_id),
  order_date    TEXT    NOT NULL,
  ship_date     TEXT,
  status        TEXT    NOT NULL,
  shipping_cost REAL    NOT NULL DEFAULT 0,
  ship_country  TEXT
);

CREATE TABLE order_items (
  order_id      INTEGER NOT NULL REFERENCES orders(order_id),
  item_no       INTEGER NOT NULL,
  product_id    INTEGER NOT NULL REFERENCES products(product_id),
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  unit_price    REAL    NOT NULL,
  discount      REAL    NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id, item_no)
);

CREATE TABLE payments (
  payment_id    INTEGER PRIMARY KEY,
  order_id      INTEGER NOT NULL REFERENCES orders(order_id),
  method        TEXT    NOT NULL,
  amount        REAL    NOT NULL,
  paid_at       TEXT    NOT NULL
);

CREATE TABLE reviews (
  review_id     INTEGER PRIMARY KEY,
  product_id    INTEGER NOT NULL REFERENCES products(product_id),
  customer_id   INTEGER NOT NULL REFERENCES customers(customer_id),
  rating        INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment       TEXT,
  created_at    TEXT    NOT NULL
);

CREATE TABLE web_sessions (
  session_id    INTEGER PRIMARY KEY,
  customer_id   INTEGER REFERENCES customers(customer_id),
  started_at    TEXT    NOT NULL,
  duration_sec  INTEGER NOT NULL,
  device        TEXT    NOT NULL,
  landing_page  TEXT    NOT NULL
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
"""

# --------------------------------------------------------------------------
# Rows
# --------------------------------------------------------------------------

def build_categories():
    cats = [
        (1, "Instruments", None),
        (2, "Audio Equipment", None),
        (3, "Accessories", None),
        (4, "Sheet Music", None),
        (10, "Guitars", 1),
        (11, "Keyboards", 1),
        (12, "Percussion", 1),
        (13, "Wind", 1),
        (20, "Microphones", 2),
        (21, "Headphones", 2),
        (22, "Audio Interfaces", 2),
        (23, "Studio Monitors", 2),
        (30, "Cables", 3),
        (31, "Stands", 3),
        (32, "Cases", 3),
        (40, "Classical Scores", 4),
        (41, "Method Books", 4),
        (100, "Electric Guitars", 10),
        (101, "Acoustic Guitars", 10),
        (102, "Bass Guitars", 10),
    ]
    return [list(c) for c in cats]


SUPPLIER_NAMES = [
    ("Nordwind Instruments", "Germany", "Hamburg", 12, 4.6),
    ("Kyoto Sound Works", "Japan", "Osaka", 21, 4.8),
    ("Cascade Audio Co.", "USA", "Portland", 5, 4.1),
    ("Rio Strings", "Brazil", "Sao Paulo", 18, 3.9),
    ("Albion Amplification", "UK", "Manchester", 9, 4.4),
    ("Maple Leaf Percussion", "Canada", "Toronto", 7, 4.0),
    ("Provence Woodwinds", "France", "Lyon", 15, 4.3),
    ("Lion City Electronics", "Singapore", "Singapore", 11, 4.5),
    ("Baltic Cases", "Sweden", "Stockholm", 14, 3.6),
    ("Outback Stands", "Australia", "Melbourne", 25, 3.4),
    ("Harbour Cables", "USA", "Boston", 3, 4.2),
    ("Alpine Editions", "Germany", "Munich", 30, None),
]

PRODUCT_SEEDS = [
    # (name, category_id, price, released_on)
    ("Stratocaster Classic 60s", 100, 1299.00, "2019-03-14"),
    ("Telecaster Roadworn", 100, 1149.50, "2020-07-01"),
    ("Les Paul Standard", 100, 2199.00, "2018-11-20"),
    ("SG Junior", 100, 899.00, "2021-05-05"),
    ("Jazzmaster Offset", 100, 1499.00, "2022-02-17"),
    ("Dreadnought D-28", 101, 2799.00, "2017-09-09"),
    ("Parlour Travel Acoustic", 101, 549.00, "2021-10-12"),
    ("Grand Concert Cedar", 101, 1199.00, "2020-01-30"),
    ("Nylon Classical CG-3", 101, 399.00, "2019-06-23"),
    ("Precision Bass 4-String", 102, 1099.00, "2018-04-02"),
    ("Jazz Bass 5-String", 102, 1349.00, "2021-08-19"),
    ("Acoustic Bass Roundback", 102, 749.00, "2022-11-11"),
    ("Stage Piano SP-88", 11, 1899.00, "2020-09-01"),
    ("Analog Synth Mono-1", 11, 1099.00, "2022-06-15"),
    ("Poly Synth Wave-8", 11, 2499.00, "2023-03-22"),
    ("Portable Keyboard K-61", 11, 449.00, "2019-12-05"),
    ("MIDI Controller 49", 11, 219.00, "2021-02-28"),
    ("Drum Kit Studio 5-Piece", 12, 1599.00, "2018-08-14"),
    ("Electronic Drum Pad X", 12, 699.00, "2022-04-07"),
    ("Cajon Flamenco", 12, 189.00, "2020-05-18"),
    ("Snare Drum Maple 14", 12, 329.00, "2019-02-11"),
    ("Cymbal Pack Ride/Crash", 12, 459.00, "2021-07-27"),
    ("Tenor Saxophone TS-200", 13, 2299.00, "2017-11-03"),
    ("Student Flute FL-100", 13, 529.00, "2020-03-09"),
    ("Bb Clarinet CL-50", 13, 699.00, "2021-01-21"),
    ("Trumpet Bronze Bell", 13, 899.00, "2019-10-16"),
    ("Condenser Mic C-414", 20, 1049.00, "2018-02-26"),
    ("Dynamic Mic SM-58", 20, 109.00, "2016-05-30"),
    ("USB Podcast Mic P-1", 20, 149.00, "2022-09-13"),
    ("Ribbon Mic R-121", 20, 899.00, "2020-11-08"),
    ("Shotgun Mic NTG-3", 20, 699.00, "2021-04-19"),
    ("Studio Headphones HD-650", 21, 399.00, "2017-07-07"),
    ("Closed-Back Monitor Phones", 21, 179.00, "2020-08-24"),
    ("Wireless Studio Phones", 21, 299.00, "2023-01-16"),
    ("In-Ear Monitors IEM-5", 21, 249.00, "2022-03-03"),
    ("2-In Audio Interface Duo", 22, 189.00, "2021-06-06"),
    ("8-In Rack Interface Octa", 22, 749.00, "2020-02-14"),
    ("Thunderbolt Interface Pro", 22, 1299.00, "2023-05-25"),
    ("Portable Field Recorder", 22, 329.00, "2019-09-28"),
    ("Studio Monitor 5in (pair)", 23, 449.00, "2018-12-12"),
    ("Studio Monitor 8in (pair)", 23, 899.00, "2021-11-02"),
    ("Subwoofer Studio 10in", 23, 599.00, "2022-07-18"),
    ("XLR Cable 6m", 30, 29.00, "2016-01-04"),
    ("Instrument Cable 3m", 30, 19.50, "2016-01-04"),
    ("Patch Cable Pack (6)", 30, 34.00, "2019-04-15"),
    ("USB-C Audio Cable", 30, 24.00, "2022-10-10"),
    ("Speaker Cable 5m", 30, 39.00, "2018-06-20"),
    ("Guitar Stand Tripod", 31, 45.00, "2017-03-30"),
    ("Keyboard Stand X-Frame", 31, 79.00, "2018-09-05"),
    ("Mic Stand Boom", 31, 59.00, "2017-10-25"),
    ("Studio Monitor Stands", 31, 129.00, "2021-09-09"),
    ("Hardshell Guitar Case", 32, 199.00, "2019-01-17"),
    ("Gig Bag Deluxe", 32, 89.00, "2020-06-11"),
    ("Flight Case Keyboard 88", 32, 349.00, "2022-01-08"),
    ("Pedalboard Case Medium", 32, 149.00, "2023-02-02"),
    ("Bach Cello Suites (Urtext)", 40, 34.00, "2015-05-05"),
    ("Chopin Nocturnes Complete", 40, 42.00, "2015-05-05"),
    ("Debussy Preludes Book I", 40, 38.00, "2016-08-08"),
    ("Guitar Method Volume 1", 41, 24.00, "2016-02-02"),
    ("Jazz Piano Voicings", 41, 32.00, "2018-03-15"),
    ("Drum Rudiments Handbook", 41, 27.50, "2019-05-20"),
]

MATERIALS = ["maple", "mahogany", "alder", "aluminium", "ABS plastic", "spruce"]
COLOURS = ["black", "sunburst", "natural", "white", "red"]


def build_products():
    products, meta = [], []
    for idx, (name, cat, price, released) in enumerate(PRODUCT_SEEDS, start=1):
        supplier = RNG.randint(1, len(SUPPLIER_NAMES))
        stock = RNG.choice([0, 0, 2, 5, 8, 12, 18, 25, 40, 60, 90, 140])
        reorder = RNG.choice([5, 10, 10, 20, None])
        discontinued = 1 if RNG.random() < 0.10 else 0
        products.append([idx, name, cat, supplier, price, stock, reorder,
                         discontinued, released])
        attrs = {
            "colour": RNG.choice(COLOURS),
            "weight_kg": round(RNG.uniform(0.2, 12.0), 2),
            "warranty_months": RNG.choice([12, 24, 36]),
            "tags": RNG.sample(["pro", "beginner", "studio", "stage", "bestseller",
                                "limited"], k=2),
        }
        if cat in (100, 101, 102, 11, 12, 13):
            attrs["material"] = RNG.choice(MATERIALS)
        as_json = (
            "{"
            + ", ".join(
                f'"{k}": ' + (
                    "[" + ", ".join(f'"{t}"' for t in v) + "]" if isinstance(v, list)
                    else (f'"{v}"' if isinstance(v, str) else str(v))
                )
                for k, v in attrs.items()
            )
            + "}"
        )
        meta.append([idx, as_json])
    return products, meta


def build_customers():
    customers = []
    for cid in range(1, 81):
        first = RNG.choice(FIRST_NAMES)
        last = RNG.choice(LAST_NAMES)
        country, cities = RNG.choice(COUNTRIES)
        city = RNG.choice(cities)
        signup = TODAY - dt.timedelta(days=RNG.randint(20, 1500))
        birth = dt.date(RNG.randint(1955, 2005), RNG.randint(1, 12), RNG.randint(1, 28))
        tier = RNG.choices(TIERS, weights=[45, 30, 18, 7])[0]
        email = f"{first.lower()}.{last.lower()}{cid}@example.com"
        # a few rows carry NULLs on purpose -- NULL handling is a lesson of its own
        if cid % 17 == 0:
            country, city = None, None
        if cid % 23 == 0:
            birth = None
        referred = RNG.randint(1, cid - 1) if cid > 10 and RNG.random() < 0.25 else None
        customers.append([cid, first, last, email, country, city, d(signup),
                          d(birth) if birth else None, tier, referred])
    return customers


EMPLOYEES = [
    # id, first, last, title, dept, manager, hire, salary, region
    (1, "Marguerite", "Okonjo", "Chief Executive Officer", "Executive", None, "2014-01-06", 240000, None),
    (2, "Henrik", "Solberg", "VP of Sales", "Sales", 1, "2015-03-02", 165000, "EMEA"),
    (3, "Priya", "Raghavan", "VP of Operations", "Operations", 1, "2015-06-15", 158000, None),
    (4, "Tom", "Delacroix", "Sales Manager", "Sales", 2, "2016-09-12", 118000, "EMEA"),
    (5, "Sofia", "Lindqvist", "Sales Manager", "Sales", 2, "2017-02-20", 121000, "AMER"),
    (6, "Kenji", "Watanabe", "Sales Manager", "Sales", 2, "2018-05-07", 112000, "APAC"),
    (7, "Ana", "Ferreira", "Sales Representative", "Sales", 4, "2019-01-14", 74000, "EMEA"),
    (8, "Liam", "O'Sullivan", "Sales Representative", "Sales", 4, "2020-08-03", 68000, "EMEA"),
    (9, "Beatriz", "Santos", "Sales Representative", "Sales", 5, "2019-11-18", 71000, "AMER"),
    (10, "Wes", "Carter", "Sales Representative", "Sales", 5, "2021-04-05", 65500, "AMER"),
    (11, "Mei", "Lin", "Sales Representative", "Sales", 6, "2020-02-24", 69000, "APAC"),
    (12, "Arjun", "Mehta", "Warehouse Supervisor", "Operations", 3, "2017-07-10", 82000, None),
    (13, "Elena", "Petrova", "Logistics Analyst", "Operations", 12, "2019-09-30", 63000, None),
    (14, "Noah", "Brennan", "Warehouse Associate", "Operations", 12, "2022-03-14", 48000, None),
    (15, "Fatima", "Haddad", "Support Lead", "Support", 3, "2018-10-01", 79000, None),
    (16, "Diego", "Morales", "Support Agent", "Support", 15, "2021-06-21", 52000, None),
    (17, "Ingrid", "Nilsen", "Support Agent", "Support", 15, "2023-01-09", 50500, None),
    (18, "Olu", "Adebayo", "Data Analyst", "Operations", 3, "2022-11-07", 88000, None),
]

SALES_REPS = [4, 5, 6, 7, 8, 9, 10, 11]

REVIEW_COMMENTS = [
    "Exactly what I needed for the studio.",
    "Solid build quality, slightly heavy.",
    "Arrived early and well packed.",
    "Great value for the price.",
    "Sound is warm but the finish scratched easily.",
    "Would buy again.",
    "Documentation could be better.",
    "Perfect for gigging.",
    "Disappointing at this price point.",
    "My students love it.",
]

LANDING_PAGES = ["/", "/catalog", "/deals", "/product", "/blog/setup-guide", "/support"]


# A few customers never place an order and a few products are never sold --
# outer joins and "find the missing rows" exercises need those empty cases.
CUSTOMERS_WITHOUT_ORDERS = {7, 19, 26, 33, 44, 51, 58, 65, 72, 79}
PRODUCTS_NEVER_SOLD = {9, 42, 54, 61}


def build_orders(customers):
    orders, items, payments = [], [], []
    buyers = [c for c in customers if c[0] not in CUSTOMERS_WITHOUT_ORDERS]
    sellable = [i for i in range(1, len(PRODUCT_SEEDS) + 1) if i not in PRODUCTS_NEVER_SOLD]
    order_id = 1000
    payment_id = 1
    start = dt.date(2023, 1, 1)
    span = (TODAY - start).days
    for _ in range(620):
        order_id += 1
        cid = RNG.choice(buyers)[0]
        order_date = start + dt.timedelta(days=RNG.randint(0, span))
        status = RNG.choice(STATUSES)
        rep = RNG.choice(SALES_REPS) if RNG.random() > 0.08 else None
        if status in ("completed", "returned"):
            ship = order_date + dt.timedelta(days=RNG.randint(1, 9))
        elif status == "shipped":
            ship = order_date + dt.timedelta(days=RNG.randint(1, 4))
        else:
            ship = None
        ship_country = None
        for c in customers:
            if c[0] == cid:
                ship_country = c[4]
                break
        shipping = round(RNG.uniform(0, 45), 2)
        orders.append([order_id, cid, rep, d(order_date),
                       d(ship) if ship else None, status, shipping, ship_country])

        n_items = RNG.choices([1, 2, 3, 4, 5], weights=[35, 28, 20, 11, 6])[0]
        chosen = RNG.sample(sellable, n_items)
        total = shipping
        for item_no, pid in enumerate(chosen, start=1):
            base = PRODUCT_SEEDS[pid - 1][2]
            qty = RNG.choices([1, 1, 1, 2, 2, 3, 4, 6], weights=[30, 20, 15, 15, 8, 6, 4, 2])[0]
            discount = RNG.choice([0, 0, 0, 0, 0.05, 0.10, 0.15, 0.20])
            price = round(base * RNG.uniform(0.97, 1.03), 2)
            total += price * qty * (1 - discount)
            items.append([order_id, item_no, pid, qty, price, discount])

        if status in ("completed", "shipped", "returned"):
            paid = (ship or order_date)
            payments.append([payment_id, order_id, RNG.choice(METHODS),
                             round(total, 2), ts(paid, RNG.randint(8, 21), RNG.randint(0, 59))])
            payment_id += 1
            # a handful of orders are settled in two instalments
            if RNG.random() < 0.05:
                payments.append([payment_id, order_id, "gift_card",
                                 round(total * 0.25, 2),
                                 ts(paid + dt.timedelta(days=1), RNG.randint(8, 21), RNG.randint(0, 59))])
                payment_id += 1
    return orders, items, payments


def build_reviews(customers):
    reviews = []
    rid = 1
    for _ in range(320):
        pid = RNG.choice([i for i in range(1, len(PRODUCT_SEEDS) + 1)
                          if i not in (9, 54, 61)])
        cid = RNG.choice(customers)[0]
        rating = RNG.choices([1, 2, 3, 4, 5], weights=[5, 8, 17, 38, 32])[0]
        comment = RNG.choice(REVIEW_COMMENTS) if RNG.random() > 0.22 else None
        created = TODAY - dt.timedelta(days=RNG.randint(1, 900))
        reviews.append([rid, pid, cid, rating, comment,
                        ts(created, RNG.randint(6, 23), RNG.randint(0, 59))])
        rid += 1
    return reviews


def build_sessions(customers):
    """One row per visit. Days are deliberately missing here and there so the
    advanced 'gaps and islands' lessons have something to find."""
    sessions = []
    sid = 1
    day = dt.date(2025, 1, 1)
    while day <= TODAY:
        # skip roughly one day in seven -> gaps in the daily series
        if RNG.random() < 0.14:
            day += dt.timedelta(days=1)
            continue
        for _ in range(RNG.randint(1, 6)):
            cid = RNG.choice(customers)[0] if RNG.random() > 0.35 else None
            sessions.append([sid, cid, ts(day, RNG.randint(0, 23), RNG.randint(0, 59)),
                             RNG.randint(20, 3600), RNG.choice(DEVICES),
                             RNG.choice(LANDING_PAGES)])
            sid += 1
        day += dt.timedelta(days=1)
    return sessions


def main() -> None:
    parts = [SCHEMA]

    categories = build_categories()
    parts.append(insert("categories", ["category_id", "name", "parent_id"], categories))

    suppliers = [[i + 1, *s] for i, s in enumerate(SUPPLIER_NAMES)]
    parts.append(insert("suppliers",
                        ["supplier_id", "name", "country", "city", "lead_time_days", "rating"],
                        suppliers))

    products, meta = build_products()
    parts.append(insert("products",
                        ["product_id", "name", "category_id", "supplier_id", "unit_price",
                         "units_in_stock", "reorder_level", "discontinued", "released_on"],
                        products))
    parts.append(insert("product_meta", ["product_id", "attributes"], meta))

    customers = build_customers()
    parts.append(insert("customers",
                        ["customer_id", "first_name", "last_name", "email", "country",
                         "city", "signup_date", "birth_date", "loyalty_tier", "referred_by"],
                        customers))

    parts.append(insert("employees",
                        ["employee_id", "first_name", "last_name", "title", "department",
                         "manager_id", "hire_date", "salary", "region"],
                        [list(e) for e in EMPLOYEES]))

    orders, items, payments = build_orders(customers)
    parts.append(insert("orders",
                        ["order_id", "customer_id", "employee_id", "order_date", "ship_date",
                         "status", "shipping_cost", "ship_country"], orders))
    parts.append(insert("order_items",
                        ["order_id", "item_no", "product_id", "quantity", "unit_price", "discount"],
                        items))
    parts.append(insert("payments",
                        ["payment_id", "order_id", "method", "amount", "paid_at"], payments))

    parts.append(insert("reviews",
                        ["review_id", "product_id", "customer_id", "rating", "comment", "created_at"],
                        build_reviews(customers)))

    parts.append(insert("web_sessions",
                        ["session_id", "customer_id", "started_at", "duration_sec", "device",
                         "landing_page"], build_sessions(customers)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
